export { Navbar } from "./Navbar"
export { Footer } from "./Footer"
export { Skill } from "./Skill"
export { Project } from "./Project"
export { Contact } from "./Contact"
export { About } from "./About"
export {Education} from "./Education"
export { Hero } from "./Hero"
export { Ed } from "./Ed"